//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5456
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class test_masters_DefaultMasterPage {
    
    /// <summary>
    /// Controllo form1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// Controllo imgCodeCarvingsLogo.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgCodeCarvingsLogo;
    
    /// <summary>
    /// Controllo imgPageBrandLogo.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgPageBrandLogo;
    
    /// <summary>
    /// Controllo pageBody.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder pageBody;
}
