'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da uno strumento.
'     Versione runtime: 2.0.50727.42
'
'     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse
'     se il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

