//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5456
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class SimpleImageUpload {
    
    /// <summary>
    /// Controllo phDesignTimeStart.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phDesignTimeStart;
    
    /// <summary>
    /// Controllo litStatusMessage.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal litStatusMessage;
    
    /// <summary>
    /// Controllo phImageContainer.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phImageContainer;
    
    /// <summary>
    /// Controllo hlPictureImageEdit.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink hlPictureImageEdit;
    
    /// <summary>
    /// Controllo imgPreview.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgPreview;
    
    /// <summary>
    /// Controllo phEditCommands.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phEditCommands;
    
    /// <summary>
    /// Controllo btnEdit.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnEdit;
    
    /// <summary>
    /// Controllo btnRemove.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnRemove;
    
    /// <summary>
    /// Controllo phUploadCommands.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phUploadCommands;
    
    /// <summary>
    /// Controllo btnBrowseDisabled.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnBrowseDisabled;
    
    /// <summary>
    /// Controllo btnCancelUpload.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnCancelUpload;
    
    /// <summary>
    /// Controllo btnBrowse.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnBrowse;
    
    /// <summary>
    /// Controllo btnPostBack.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnPostBack;
    
    /// <summary>
    /// Controllo litScript.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal litScript;
    
    /// <summary>
    /// Controllo hfAct.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfAct;
    
    /// <summary>
    /// Controllo litSelectConfiguration.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal litSelectConfiguration;
    
    /// <summary>
    /// Controllo ddlConfigurations.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlConfigurations;
    
    /// <summary>
    /// Controllo popupPictureTrimmer1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::CodeCarvings.Piczard.Web.PopupPictureTrimmer popupPictureTrimmer1;
    
    /// <summary>
    /// Controllo phDesignTimeEnd.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phDesignTimeEnd;
}
