//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5456
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class SimpleImageUpload_upload {
    
    /// <summary>
    /// Controllo form1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// Controllo phMainContainer.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder phMainContainer;
    
    /// <summary>
    /// Controllo fuFile.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.FileUpload fuFile;
    
    /// <summary>
    /// Controllo ddlDummyForceDoPostBackCreation.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlDummyForceDoPostBackCreation;
    
    /// <summary>
    /// Controllo btnUpload.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnUpload;
}
