//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5456
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class test_default {
    
    /// <summary>
    /// Controllo ScriptManager1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// Controllo UpdatePanel1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel UpdatePanel1;
    
    /// <summary>
    /// Controllo ImageUpload1.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::SimpleImageUpload ImageUpload1;
    
    /// <summary>
    /// Controllo ImageUpload2.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::SimpleImageUpload ImageUpload2;
    
    /// <summary>
    /// Controllo btnDummyPostback.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnDummyPostback;
}
